server:
  port: 8283

logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.cp: DEBUG
    me.chanjar.weixin: DEBUG

spring:
  jackson:
    time-zone: GMT+8

qy:
  wx:
    corpId: 111
    appConfigs:
      - agentId: 1000001
        secret: 1111
        token: 111
        aesKey: 111
      - agentId: 1000002
        ecret: 1111
        token: 111
        aesKey: 111